-- dim_dates — Type 1 calendar dimension, generated by dbt_date.
-- Covers the GH Archive backfill (2024-01-01) through a forward margin.
-- date_day is the natural PK. Rebuild with --full-refresh to widen.

{{ dbt_date.get_date_dimension("2024-01-01", "2027-12-31") }}
